name = "FloatingPointErrors"
uuid = "3887ebbf-9bf7-4029-8622-e5aebe3d2d65"
authors = ["David Gleich <dgleich@purdue.edu>"]
version = "0.1.0"

[deps]
MultiFloats = "bdf0d083-296b-4888-a5b6-7498122e68a5"

[compat]
MultiFloats = "2.3.0"
